thor_config = {
    "room_types": {
        "kitchen.r": range(1,31),
        "living_room.r": range(201,231),
        "bedroom.r": range(301,331),
        "bathroom.r": range(401,431)
    },
    "room_seeds": range(10),
    "actions": ["open.a","close.a",
                "pickup.a","put.a",
                "drop.a","thorw.a",
                "switchon.a","switchoff.a",
                "fill.a","pour.a","empty.a",
                "slice.a","break.a",
                # added to enrich actions, not directly in AI2Thor
                # clean.s/dirty.s related:
                "rinse.a","wash.a","scrub.a","wipe.a","sweep.a","vacuum.a","dust.a",
                "stow.a","discard.a","recycle.a","mop.a",
                # cook.s related:
                "toast.a","microwave.a","bake.a","fry.a","boil.a","brew.a"],
    "states": ["opened.s","closed.s",
               "on.s","off.s",
               "full.s","empty.s",
               "sliced.s","whole.s",
               "cooked.s","uncooked.s",
               "broken.s","notbroken.s",
               "dirty.s","clean.s"],
    "triple_rules": {
        "action_inverseActionOf": {
            "open.a": ["close.a"],
            "close.a": ["open.a"],
            "pickup.a": ["put.a","drop.a"],
            "put.a": ["pickup.a"],
            "drop.a": ["pickup.a"],
            "switchon.a": ["switchoff.a"],
            "switchoff.a": ["switchon.a"],
            "fill.a": ["pour.a","empty.a"],
            "pour.a": ["fill.a"],
            "empty.a": ["fill.a"]
        },
        "state_inverseStateOf": {
            "opened.s": ["closed.s"],
            "closed.s": ["opened.s"],
            "on.s": ["off.s"],
            "off.s": ["on.s"],
            "full.s": ["empty.s"],
            "empty.s": ["full.s"],
            "sliced.s": ["whole.s"],
            "whole.s": ["sliced.s"],
            "cooked.s": ["uncooked.s"],
            "uncooked.s": ["cooked.s"],
            "broken.s": ["notbroken.s"],
            "notbroken.s": ["broken.s"],
            "dirty.s": ["clean.s"],
            "clean.s": ["dirty.s"]
        },
        "action_hasEffect": {
            "open.a": ["opened.s"],
            "close.a": ["closed.s"],
            "switchon.a": ["on.s"],
            "switchoff.a": ["off.s"],
            "fill.a": ["full.s"],
            "pour.a": ["empty.s"],
            "empty.a": ["empty.s"],
            "slice.a": ["sliced.s"],
            "break.a": ["broken.s"],
            # added to enrich actions, not directly in AI2Thor
            "rinse.a": ["clean.s"],
            "wash.a": ["clean.s"],
            "scrub.a": ["clean.s"],
            "wipe.a": ["clean.s"],
            "sweep.a": ["clean.s"],
            "vacuum.a": ["clean.s"],
            "dust.a": ["clean.s"],
            "stow.a": ["clean.s"],
            "discard.a": ["clean.s"],
            "recycle.a": ["clean.s"],
            "mop.a": ["clean.s"],
            "toast.a": ["cooked.s"],
            "microwave.a": ["cooked.s"],
            "bake.a": ["cooked.s"],
            "fry.a": ["cooked.s"],
            "brew.a": ["cooked.s"],
            "boil.a": ["cooked.s"],
        },
        "obj_canBe": {
            "alarmclock.o": ["pickup.a","put.a","dust.a"],
            "apple.o": ["pickup.a","put.a","slice.a","rinse.a","stow.a","discard.a","bake.a"],
            "armchair.o": ["fill.a","empty.a","vacuum.a"],
            "baseballbat.o": ["pickup.a","put.a","stow.a"],
            "basketball.o": ["pickup.a","put.a","stow.a"],
            "bathtub.o": ["scrub.a","wipe.a"],
            "bathtubbasin.o": ["fill.a","empty.a","scrub.a","wipe.a"],
            "bed.o": ["fill.a","empty.a","vacuum.a"],
            "blinds.o": ["open.a","close.a","dust.a"],
            "book.o": ["open.a","close.a","pickup.a","put.a","dust.a","stow.a"],
            "boots.o": ["pickup.a","put.a","wash.a","stow.a"],
            "bowl.o": ["pickup.a","put.a","fill.a","empty.a","pour.a","rinse.a","wash.a","scrub.a","stow.a"],
            "box.o": ["open.a","close.a","pickup.a","put.a","fill.a","empty.a","dust.a","stow.a","recycle.a"],
            "bread.o": ["pickup.a","put.a","slice.a","stow.a","discard.a","toast.a","bake.a"],
            "butterknife.o": ["pickup.a","put.a","rinse.a","wash.a","scrub.a","stow.a"],
            "cabinet.o": ["open.a","close.a","fill.a","empty.a","wipe.a","dust.a"],
            "candle.o": ["pickup.a","put.a","switchon.a","switchoff.a","stow.a","discard.a"],
            "cart.o": ["fill.a","empty.a"],
            "cd.o": ["pickup.a","put.a","wipe.a","stow.a"],
            "cellphone.o": ["pickup.a","put.a","switchon.a","switchoff.a","break.a","wipe.a","stow.a"],
            "chair.o": ["wipe.a","vacuum.a"],
            "cloth.o": ["pickup.a","put.a","wash.a","stow.a"],
            "coffeemachine.o": ["switchon.a","switchoff.a","fill.a","empty.a","wipe.a"],
            "coffeetable.o": ["fill.a","empty.a","wipe.a","dust.a"],
            "countertop.o": ["fill.a","empty.a","scrub.a","wipe.a"],
            "creditcard.o": ["pickup.a","put.a","stow.a"],
            "cup.o": ["pickup.a","put.a","fill.a","empty.a","pour.a","rinse.a","wash.a","scrub.a","stow.a","recycle.a"],
            "curtains.o": ["wash.a","vacuum.a","dust.a"],
            "desk.o": ["fill.a","empty.a","wipe.a"],
            "desklamp.o": ["switchon.a","switchoff.a","dust.a","stow.a"],
            "diningtable.o": ["fill.a","empty.a","wipe.a","dust.a"],
            "dishsponge.o": ["pickup.a","put.a","rinse.a","stow.a","discard.a"],
            "drawer.o": ["open.a","close.a","fill.a","empty.a","wipe.a","dust.a"],
            "dresser.o": ["fill.a","empty.a","wipe.a","dust.a"],
            "egg.o": ["pickup.a","put.a","slice.a","break.a","stow.a","discard.a","microwave.a","fry.a","boil.a"],
            "faucet.o": ["switchon.a","switchoff.a","scrub.a","wipe.a"],
            "floorlamp.o": ["switchon.a","switchoff.a","dust.a"],
            "floor.o": ["scrub.a","wipe.a","sweep.a","vacuum.a","mop.a",],
            "footstool.o": [],
            "fork.o": ["pickup.a","put.a","rinse.a","wash.a","scrub.a","stow.a","recycle.a"],
            "fridge.o": ["open.a","close.a","fill.a","empty.a","wipe.a"],
            "garbagecan.o": ["fill.a","empty.a"],
            "glassbottle.o": ["fill.a","pour.a","break.a","rinse.a","wash.a","stow.a","recycle.a"],
            "handtowel.o": ["pickup.a","put.a","wash.a","stow.a"],
            "handtowelholder.o": ["fill.a","empty.a"],
            "houseplant.o": ["fill.a","pour.a"],
            "kettle.o": ["open.a","close.a","pickup.a","put.a","fill.a","pour.a","rinse.a","wash.a","scrub.a","stow.a"],
            "keychain.o": ["pickup.a","put.a","stow.a"],
            "knife.o": ["pickup.a","put.a","rinse.a","wash.a","scrub.a","stow.a","recycle.a"],
            "ladle.o": ["pickup.a","put.a","rinse.a","wash.a","scrub.a","stow.a"],
            "lamp.o": ["switchon.a","switchoff.a","dust.a"],
            "laptop.o": ["open.a","close.a","pickup.a","put.a","switchon.a","switchoff.a","break.a","wipe.a","dust.a","stow.a"],
            "laundryhamper.o": ["fill.a","empty.a"],
            "laundryhamperlid.o": ["open.a","close.a"],
            "lettuce.o": ["pickup.a","put.a","slice.a","rinse.a","stow.a","discard.a"],
            "lightswitch.o": ["switchon.a","switchoff.a"],
            "microwave.o": ["open.a","close.a","switchon.a","switchoff.a","fill.a","empty.a","wipe.a"],
            "mirror.o": ["break.a","wipe.a"],
            "mug.o": ["pickup.a","put.a","fill.a","empty.a","pour.a","break.a","rinse.a","wash.a","scrub.a","stow.a"],
            "newspaper.o": ["pickup.a","put.a","stow.a","recycle.a"],
            "nightstand.o": ["wipe.a","dust.a"],
            "ottoman.o": ["fill.a","empty.a","vacuum.a","dust.a"],
            "painting.o": ["dust.a"],
            "pan.o": ["pickup.a","put.a","fill.a","empty.a","rinse.a","wash.a","scrub.a","stow.a"],
            "papertowelroll.o": ["pickup.a","put.a","stow.a","recycle.a"],
            "pen.o": ["pickup.a","put.a","stow.a","discard.a"],
            "pencil.o": ["pickup.a","put.a","stow.a","discard.a"],
            "peppershaker.o": ["pickup.a","put.a","stow.a"],
            "pillow.o": ["pickup.a","put.a","wash.a","stow.a"],
            "plate.o": ["pickup.a","put.a","fill.a","empty.a","rinse.a","wash.a","scrub.a","stow.a","recycle.a"],
            "plunger.o": ["pickup.a","put.a","stow.a"],
            "poster.o": ["dust.a"],
            "pot.o": ["pickup.a","put.a","fill.a","empty.a","pour.a","rinse.a","wash.a","scrub.a","stow.a"],
            "potato.o": ["pickup.a","put.a","slice.a","rinse.a","stow.a","discard.a","microwave.a","bake.a","fry.a","boil.a"],
            "remotecontrol.o": ["pickup.a","put.a","stow.a"],
            "safe.o": ["open.a","close.a","fill.a","empty.a","wipe.a","dust.a"],
            "saltshaker.o": ["pickup.a","put.a","stow.a"],
            "scrubbrush.o": ["pickup.a","put.a","rinse.a","stow.a"],
            "shelf.o": ["fill.a","empty.a","wipe.a","dust.a"],
            "showercurtain.o": ["open.a","close.a","wash.a"],
            "showerdoor.o": ["open.a","close.a","break.a","scrub.a","wipe.a"],
            "showerglass.o": ["break.a","scrub.a","wipe.a"],
            "showerhead.o": ["switchon.a","switchoff.a"],
            "sidetable.o": ["fill.a","empty.a","wipe.a","dust.a"],
            "sink.o": ["scrub.a"],
            "sinkbasin.o": ["fill.a","empty.a","scrub.a"],
            "soapbar.o": ["pickup.a","put.a","stow.a","discard.a"],
            "soapbottle.o": ["pickup.a","put.a","stow.a","discard.a"],
            "sofa.o": ["fill.a","empty.a","vacuum.a"],
            "spatula.o": ["pickup.a","put.a","rinse.a","wash.a","scrub.a","stow.a"],
            "spoon.o": ["pickup.a","put.a","rinse.a","wash.a","scrub.a","stow.a","discard.a","recycle.a"],
            "spraybottle.o": ["pickup.a","put.a","stow.a","discard.a"],
            "statue.o": ["pickup.a","put.a","break.a","wipe.a","dust.a"],
            "stoveburner.o": ["switchon.a","switchoff.a","fill.a","empty.a","scrub.a"],
            "stoveknob.o": ["switchon.a","switchoff.a"],
            "tabletop.o": ["fill.a","empty.a","scrub.a","wipe.a"],
            "teddybear.o": ["pickup.a","put.a","wash.a","stow.a"],
            "television.o": ["switchon.a","switchoff.a","break.a","dust.a"],
            "tennisracket.o": ["pickup.a","put.a","stow.a"],
            "tissuebox.o": ["pickup.a","put.a","discard.a"],
            "toaster.o": ["switchon.a","switchoff.a","fill.a","empty.a"],
            "toilet.o": ["fill.a","empty.a","scrub.a"],
            "toiletpaper.o": ["pickup.a","put.a","stow.a","discard.a"],
            "toiletpaperhanger.o": ["fill.a","empty.a"],
            "tomato.o": ["pickup.a","put.a","slice.a","rinse.a","stow.a","discard.a","fry.a"],
            "towel.o": ["pickup.a","put.a","wash.a","stow.a"],
            "towelholder.o": ["fill.a","empty.a"],
            "tvstand.o": ["fill.a","empty.a","wipe.a","dust.a"],
            "vase.o": ["pickup.a","put.a","break.a","wipe.a","dust.a","stow.a"],
            "watch.o": ["pickup.a","put.a","stow.a"],
            "wateringcan.o": ["pickup.a","put.a","fill.a","pour.a","stow.a"],
            "window.o": ["break.a","scrub.a","wipe.a"],
            "winebottle.o": ["pickup.a","put.a","fill.a","pour.a","break.a","stow.a","recycle.a"],
            "shelvingunit.o": ["fill.a","emtpy.a"],
            "garbagebag.o": ["pickup.a","put.a","fill.a","empty.a","stow.a"],
            "stool.o": ["pickup.a","put.a"],
            "bottle.o": ["pickup.a","put.a","fill.a","pour.a","break.a","stow.a","recycle.a"],
            "aluminumfoil.o": ["pickup.a","put.a","fill.a","empty.a","stow.a"],
            "dogbed.o": [],
            "roomdecor.o": [],
            "tabletopdecor.o": [],
            "vacuumcleaner.o": ["switchon.a","switchoff.a","pickup.a","stow.a","put.a"],
            "desktop.o": ["switchon.a","switchoff.a"],
            "dumbbell.o": ["pickup.a","put.a","stow.a"],
        },
        "obj_usedTo": {
            "alarmclock.o": [],
            "apple.o": [],
            "armchair.o": [],
            "baseballbat.o": [],
            "basketball.o": [],
            "bathtub.o": [],
            "bathtubbasin.o": [],
            "bed.o": [],
            "blinds.o": [],
            "book.o": [],
            "boots.o": [],
            "bowl.o": ["pour.a"],
            "box.o": [],
            "bread.o": [],
            "butterknife.o": ["slice.a"],
            "cabinet.o": [],
            "candle.o": [],
            "cart.o": [],
            "cd.o": [],
            "cellphone.o": [],
            "chair.o": [],
            "cloth.o": ["scrub.a","wipe.a"],
            "coffeemachine.o": ["brew.a"],
            "coffeetable.o": [],
            "countertop.o": [],
            "creditcard.o": [],
            "cup.o": ["pour.a"],
            "curtains.o": [],
            "desk.o": [],
            "desklamp.o": [],
            "diningtable.o": [],
            "dishsponge.o": ["scrub.a"],
            "drawer.o": [],
            "dresser.o": [],
            "egg.o": [],
            "faucet.o": ["rinse.a"],
            "floorlamp.o": [],
            "floor.o": [],
            "footstool.o": [],
            "fork.o": [],
            "fridge.o": [],
            "garbagecan.o": ["discard.a"],
            "glassbottle.o": ["pour.a"],
            "handtowel.o": ["scrub.a","wipe.a","dust.a"],
            "handtowelholder.o": [],
            "houseplant.o": [],
            "kettle.o": [],
            "keychain.o": [],
            "knife.o": ["slice.a"],
            "ladle.o": ["pour.a"],
            "lamp.o": [],
            "laptop.o": [],
            "laundryhamper.o": [],
            "laundryhamperlid.o": [],
            "lettuce.o": [],
            "lightswitch.o": [],
            "microwave.o": ["microwave.a"],
            "mirror.o": [],
            "mug.o": ["pour.a"],
            "newspaper.o": [],
            "nightstand.o": [],
            "ottoman.o": [],
            "painting.o": [],
            "pan.o": [],
            "papertowelroll.o": [],
            "pen.o": [],
            "pencil.o": [],
            "peppershaker.o": [],
            "pillow.o": [],
            "plate.o": [],
            "plunger.o": [],
            "poster.o": [],
            "pot.o": [],
            "potato.o": [],
            "remotecontrol.o": [],
            "safe.o": [],
            "saltshaker.o": [],
            "scrubbrush.o": ["scrub.a"],
            "shelf.o": [],
            "showercurtain.o": [],
            "showerdoor.o": [],
            "showerglass.o": [],
            "showerhead.o": ["rinse.a"],
            "sidetable.o": [],
            "sink.o": ["rinse.a"],
            "sinkbasin.o": [],
            "soapbar.o": [],
            "soapbottle.o": [],
            "sofa.o": [],
            "spatula.o": [],
            "spoon.o": [],
            "spraybottle.o": [],
            "statue.o": [],
            "stoveburner.o": ["fry.a","boil.a","brew.a"],
            "stoveknob.o": [],
            "tabletop.o": [],
            "teddybear.o": [],
            "television.o": [],
            "tennisracket.o": [],
            "tissuebox.o": [],
            "toaster.o": ["toast.a"],
            "toilet.o": [],
            "toiletpaper.o": [],
            "toiletpaperhanger.o": [],
            "tomato.o": [],
            "towel.o": ["scrub.a","wipe.a","dust.a"],
            "towelholder.o": [],
            "tvstand.o": [],
            "vase.o": ["pour.a"],
            "watch.o": [],
            "wateringcan.o": ["pour.a"],
            "window.o": [],
            "winebottle.o": ["pour.a"],
            "shelvingunit.o": [],
            "garbagebag.o": ["discard.a"],
            "stool.o": [],
            "bottle.o": ["pour.a"],
            "aluminumfoil.o": [],
            "dogbed.o": [],
            "roomdecor.o": [],
            "tabletopdecor.o": [],
            "vacuumcleaner.o": ["vacuum.a"],
            "desktop.o": [],
            "dumbbell.o": [],
        },
        "obj_hasState": {
            "alarmclock.o": [],
            "apple.o": ["sliced.s","whole.s","cooked.s","uncooked.s"],
            "armchair.o": ["full.s","empty.s"],
            "baseballbat.o": [],
            "basketball.o": [],
            "bathtub.o": ["dirty.s","clean.s"],
            "bathtubbasin.o": ["full.s","empty.s"],
            "bed.o": ["full.s","empty.s","dirty.s","clean.s"],
            "blinds.o": ["opened.s","closed.s"],
            "book.o": ["opened.s","closed.s"],
            "boots.o": [],
            "bowl.o": ["full.s","empty.s","dirty.s","clean.s"],
            "box.o": ["opened.s","closed.s","full.s","empty.s"],
            "bread.o": ["sliced.s","whole.s","cooked.s","uncooked.s"],
            "butterknife.o": [],
            "cabinet.o": ["opened.s","closed.s","full.s","empty.s"],
            "candle.o": ["on.s","off.s"],
            "cart.o": ["full.s","empty.s"],
            "cd.o": [],
            "cellphone.o": ["on.s","off.s","broken.s"],
            "chair.o": ["dirty.s","clean.s"],
            "cloth.o": ["dirty.s","clean.s"],
            "coffeemachine.o": ["on.s","off.s","full.s","empty.s"],
            "coffeetable.o": ["full.s","empty.s"],
            "countertop.o": ["full.s","empty.s","dirty.s","clean.s"],
            "creditcard.o": [],
            "cup.o": ["full.s","empty.s","dirty.s","clean.s"],
            "curtains.o": ["dirty.s","clean.s"],
            "desk.o": ["full.s","empty.s","dirty.s","clean.s"],
            "desklamp.o": ["on.s","off.s","dirty.s","clean.s"],
            "diningtable.o": ["full.s","empty.s"],
            "dishsponge.o": ["dirty.s","clean.s"],
            "drawer.o": ["opened.s","closed.s","full.s","empty.s"],
            "dresser.o": ["full.s","empty.s","dirty.s","clean.s"],
            "egg.o": ["sliced.s","whole.s","cooked.s","uncooked.s","broken.s"],
            "faucet.o": ["on.s","off.s"],
            "floorlamp.o": ["on.s","off.s"],
            "floor.o": ["dirty.s","clean.s",],
            "footstool.o": [],
            "fork.o": [],
            "fridge.o": ["opened.s","closed.s","full.s","empty.s"],
            "garbagecan.o": ["full.s","empty.s"],
            "glassbottle.o": [],
            "handtowel.o": [],
            "handtowelholder.o": ["full.s","empty.s"],
            "houseplant.o": ["full.s","empty.s"],
            "kettle.o": ["opened.s","closed.s","full.s","empty.s"],
            "keychain.o": [],
            "knife.o": [],
            "ladle.o": [],
            "lamp.o": [],
            "laptop.o": ["opened.s","closed.s","on.s","off.s","broken.s"],
            "laundryhamper.o": ["full.s","empty.s"],
            "laundryhamperlid.o": ["opened.s","closed.s"],
            "lettuce.o": ["sliced.s","whole.s","uncooked.s"],
            "lightswitch.o": ["on.s","off.s"],
            "microwave.o": ["opened.s","closed.s","on.s","off.s","full.s","empty.s","dirty.s","clean.s"],
            "mirror.o": ["broken.s","dirty.s","clean.s"],
            "mug.o": ["full.s","empty.s","broken.s","dirty.s","clean.s"],
            "newspaper.o": [],
            "nightstand.o": ["full.s","empty.s"],
            "ottoman.o": ["full.s","empty.s","dirty.s","clean.s"],
            "painting.o": ["dirty.s","clean.s"],
            "pan.o": ["full.s","empty.s","dirty.s","clean.s"],
            "papertowelroll.o": [],
            "pen.o": [],
            "pencil.o": [],
            "peppershaker.o": [],
            "pillow.o": [],
            "plate.o": ["full.s","empty.s","dirty.s","clean.s"],
            "plunger.o": [],
            "poster.o": [],
            "pot.o": ["full.s","empty.s","dirty.s","clean.s"],
            "potato.o": ["sliced.s","whole.s","cooked.s","uncooked.s"],
            "remotecontrol.o": [],
            "safe.o": ["opened.s","closed.s","full.s","empty.s"],
            "saltshaker.o": [],
            "scrubbrush.o": [],
            "shelf.o": ["full.s","empty.s"],
            "showercurtain.o": ["opened.s","closed.s"],
            "showerdoor.o": ["opened.s","closed.s","broken.s"],
            "showerglass.o": ["broken.s"],
            "showerhead.o": ["on.s","off.s"],
            "sidetable.o": ["full.s","empty.s"],
            "sink.o": ["dirty.s","clean.s"],
            "sinkbasin.o": ["full.s","empty.s"],
            "soapbar.o": [],
            "soapbottle.o": ["broken.s"],
            "sofa.o": ["full.s","empty.s"],
            "spatula.o": [],
            "spoon.o": [],
            "spraybottle.o": ["broken.s"],
            "statue.o": ["broken.s"],
            "stoveburner.o": ["on.s","off.s","full.s","empty.s"],
            "stoveknob.o": [],
            "tabletop.o": ["dirty.s","clean.s"],
            "teddybear.o": [],
            "television.o": ["on.s","off.s","broken.s"],
            "tennisracket.o": [],
            "tissuebox.o": [],
            "toaster.o": ["on.s","off.s","full.s","empty.s"],
            "toilet.o": ["full.s","empty.s","dirty.s","clean.s"],
            "toiletpaper.o": [],
            "toiletpaperhanger.o": ["full.s","empty.s"],
            "tomato.o": ["sliced.s","whole.s"],
            "towel.o": [],
            "towelholder.o": ["full.s","empty.s"],
            "tvstand.o": ["full.s","empty.s"],
            "vase.o": ["broken.s"],
            "watch.o": [],
            "wateringcan.o": ["full.s","empty.s"],
            "window.o": ["broken.s"],
            "winebottle.o": ["full.s","empty.s","broken.s"],
            "shelvingunit.o": ["full.s","empty.s"],
            "garbagebag.o": ["full.s","empty.s","clean.s","dirty.s"],
            "stool.o": ["full.s","empty.s"],
            "bottle.o": ["full.s","empty.s"],
            "aluminumfoil.o": [],
            "dogbed.o": ["full.s","empty.s"],
            "roomdecor.o": [],
            "tabletopdecor.o": [],
            "vacuumcleaner.o": ["clean.s","dirty.s","full.s","empty.s","broken.s"],
            "desktop.o": ["on.s","off.s"],
            "dumbbell.o": [],
        },
        "obj_OperatesOn": {
            "alarmclock.o": [],
            "apple.o": [],
            "armchair.o": [],
            "baseballbat.o": [],
            "basketball.o": [],
            "bathtub.o": [],
            "bathtubbasin.o": [],
            "bed.o": [],
            "blinds.o": [],
            "book.o": [],
            "boots.o": [],
            "bowl.o": ["apple.o","egg.o","potato.o","tomato.o"],
            "box.o": [],
            "bread.o": [],
            "butterknife.o": ["bread.o"],
            "cabinet.o": [],
            "candle.o": [],
            "cart.o": [],
            "cd.o": [],
            "cellphone.o": [],
            "chair.o": [],
            "cloth.o": ["bathtub.o","bathtubbasin.o","bowl.o","butterknife.o","countertop.o",
                        "faucet.o","cup.o","faucet.o","fork.o","kettle.o","knife.o","ladle.o","mug.o",
                        "pan.o","plate.o","pot.o","showerdoor.o","showerglass.o","sink.o","sinkbasin.o",
                        "spatula.o","spoon.o","stoveburner.o","tabletop.o","toilet.o","window.o","cabinet.o",
                        "cd.o","cellphone.o","chair.o","coffeemachine.o","countertop.o","desk.o","drawer.o",
                        "dresser.o","faucet.o","fridge.o","laptop.o","microwave.o","mirror.o","nightstand.o",
                        "safe.o","shelf.o","showerdoor.o","showerglass.o","statue.o","tabletop.o","vase.o",
                        "window.o"],
            "coffeemachine.o": [],
            "coffeetable.o": [],
            "countertop.o": [],
            "creditcard.o": [],
            "cup.o": [],
            "curtains.o": [],
            "desk.o": [],
            "desklamp.o": [],
            "diningtable.o": [],
            "dishsponge.o": ["bowl.o","butterknife.o","faucet.o","cup.o","faucet.o","fork.o",
                             "kettle.o","knife.o","ladle.o","mug.o","pan.o","plate.o","pot.o",
                             "sink.o","sinkbasin.o","spatula.o","spoon.o","stoveburner.o"],
            "drawer.o": [],
            "dresser.o": [],
            "egg.o": [],
            "faucet.o": ["apple.o","bowl.o","butterknife.o","cup.o","dishsponge.o","fork.o","glassbottle.o"
                         "kettle.o","knife.o","ladle.o","lettuce.o","mug.o","pan.o","plate.o","pot.o",
                         "potato.o","scrubbrush.o","spatula.o","spoon.o","tomato.o"],
            "floorlamp.o": [],
            "floor.o": [],
            "footstool.o": [],
            "fork.o": [],
            "fridge.o": [],
            "garbagecan.o": ["apple.o","bread.o","candle.o","dishsponge.o","egg.o","lettuce.o","pen.o","pencil.o",
                             "potato.o","soapbar.o","soapbottle.o","spoon.o","spraybottle.o","tissuebox.o",
                             "toiletpaper.o","tomato.o"],
            "glassbottle.o": [],
            "handtowel.o": ["bathtub.o","bathtubbasin.o","bowl.o","butterknife.o","countertop.o",
                        "faucet.o","cup.o","faucet.o","fork.o","kettle.o","knife.o","ladle.o","mug.o",
                        "pan.o","plate.o","pot.o","showerdoor.o","showerglass.o","sink.o","sinkbasin.o",
                        "spatula.o","spoon.o","stoveburner.o","tabletop.o","toilet.o","window.o",
                        "cabinet.o","cd.o","cellphone.o","chair.o","coffeemachine.o","countertop.o","desk.o",
                        "drawer.o","dresser.o","faucet.o","fridge.o","laptop.o","microwave.o","mirror.o",
                        "nightstand.o","safe.o","shelf.o","showerdoor.o","showerglass.o","statue.o","tabletop.o",
                        "vase.o",
                        "alarmclock.o","blinds.o","book.o","box.o","curtains.o","desklamp.o","drawer.o",
                        "dresser.o","floorlamp.o","lamp.o","laptop.o","nightstand.o","ottoman.o","painting.o",
                        "poster.o","television.o"],
            "handtowelholder.o": [],
            "houseplant.o": [],
            "kettle.o": [],
            "keychain.o": [],
            "knife.o": ["apple.o","bread.o","egg.o","potato.o","tomato.o"],
            "ladle.o": [],
            "lamp.o": [],
            "laptop.o": [],
            "laundryhamper.o": [],
            "laundryhamperlid.o": [],
            "lettuce.o": [],
            "lightswitch.o": [],
            "microwave.o": ["egg.o","potato.o"],
            "mirror.o": [],
            "mug.o": [],
            "newspaper.o": [],
            "nightstand.o": [],
            "ottoman.o": [],
            "painting.o": [],
            "pan.o": [],
            "papertowelroll.o": [],
            "pen.o": [],
            "pencil.o": [],
            "peppershaker.o": [],
            "pillow.o": [],
            "plate.o": [],
            "plunger.o": [],
            "poster.o": [],
            "pot.o": [],
            "potato.o": [],
            "remotecontrol.o": [],
            "safe.o": [],
            "saltshaker.o": [],
            "scrubbrush.o": ["bathtub.o","bathtubbasin.o","bowl.o","butterknife.o","countertop.o",
                        "faucet.o","cup.o","faucet.o","fork.o","kettle.o","knife.o","ladle.o","mug.o",
                        "pan.o","plate.o","pot.o","showerdoor.o","showerglass.o","sink.o","sinkbasin.o",
                        "spatula.o","spoon.o","stoveburner.o","tabletop.o","toilet.o","window.o"],
            "shelf.o": [],
            "showercurtain.o": [],
            "showerdoor.o": [],
            "showerglass.o": [],
            "showerhead.o": [],
            "sidetable.o": [],
            "sink.o": ["apple.o","bowl.o","butterknife.o","cup.o","dishsponge.o","fork.o","glassbottle.o"
                       "kettle.o","knife.o","ladle.o","lettuce.o","mug.o","pan.o","plate.o","pot.o",
                       "potato.o","scrubbrush.o","spatula.o","spoon.o","tomato.o"],
            "sinkbasin.o": [],
            "soapbar.o": [],
            "soapbottle.o": [],
            "sofa.o": [],
            "spatula.o": [],
            "spoon.o": [],
            "spraybottle.o": [],
            "statue.o": [],
            "stoveburner.o": ["egg.o","potato.o","tomato.o"],
            "stoveknob.o": [],
            "tabletop.o": [],
            "teddybear.o": [],
            "television.o": [],
            "tennisracket.o": [],
            "tissuebox.o": [],
            "toaster.o": ["bread.o"],
            "toilet.o": [],
            "toiletpaper.o": [],
            "toiletpaperhanger.o": [],
            "tomato.o": [],
            "towel.o": ["bathtub.o","bathtubbasin.o","bowl.o","butterknife.o","countertop.o",
                        "faucet.o","cup.o","faucet.o","fork.o","kettle.o","knife.o","ladle.o","mug.o",
                        "pan.o","plate.o","pot.o","showerdoor.o","showerglass.o","sink.o","sinkbasin.o",
                        "spatula.o","spoon.o","stoveburner.o","tabletop.o","toilet.o","window.o","cabinet.o",
                        "cd.o","cellphone.o","chair.o","coffeemachine.o","countertop.o","desk.o","drawer.o",
                        "dresser.o","faucet.o","fridge.o","laptop.o","microwave.o","mirror.o","nightstand.o",
                        "safe.o","shelf.o","showerdoor.o","showerglass.o","statue.o","tabletop.o","vase.o",
                        "window.o","alarmclock.o","blinds.o","book.o","box.o","curtains.o","desklamp.o","drawer.o",
                        "dresser.o","floorlamp.o","lamp.o","laptop.o","nightstand.o","ottoman.o","painting.o",
                        "poster.o","television.o"],
            "towelholder.o": [],
            "tvstand.o": [],
            "vase.o": [],
            "watch.o": [],
            "wateringcan.o": [],
            "window.o": [],
            "winebottle.o": [],
            "shelvingunit.o": [],
            "garbagebag.o": ["apple.o","bread.o","candle.o","dishsponge.o","egg.o","lettuce.o","pen.o","pencil.o",
                             "potato.o","soapbar.o","soapbottle.o","spoon.o","spraybottle.o","tissuebox.o",
                             "toiletpaper.o","tomato.o"],
            "stool.o": [],
            "bottle.o": [],
            "aluminumfoil.o": [],
            "dogbed.o": [],
            "roomdecor.o": [],
            "tabletopdecor.o": [],
            "vacuumcleaner.o": ["floor.o"],
            "desktop.o": [],
            "dumbbell.o": [],
        },
        "receptacle_InOn": {
            "armchair.l": "ObjOnLoc",
            "bathtub.l": "ObjInLoc",
            "bathtubbasin.l": "ObjInLoc",
            "bed.l": "ObjOnLoc",
            "bowl.l": "ObjInLoc",
            "box.l": "ObjInLoc",
            "cabinet.l": "ObjInLoc",
            "cart.l": "ObjInLoc",
            "chair.l": "ObjOnLoc",
            "coffeemachine.l": "ObjInLoc",
            "coffeetable.l": "ObjOnLoc",
            "countertop.l": "ObjOnLoc",
            "cup.l": "ObjInLoc",
            "desk.l": "ObjOnLoc",
            "diningtable.l": "ObjOnLoc",
            "drawer.l": "ObjInLoc",
            "dresser.l": "ObjOnLoc",
            "fridge.l": "ObjInLoc",
            "floor.l": "ObjOnLoc",
            "footstool.l": "ObjOnLoc",
            "garbagecan.l": "ObjInLoc",
            "handtowelholder.l": "ObjOnLoc",
            "laundryhamper.l": "ObjInLoc",
            "microwave.l": "ObjInLoc",
            "mug.l": "ObjInLoc",
            "nightstand.l": "ObjOnLoc",
            "ottoman.l": "ObjOnLoc",
            "pan.l": "ObjInLoc",
            "plate.l": "ObjOnLoc",
            "pot.l": "ObjInLoc",
            "safe.l": "ObjInLoc",
            "shelf.l": "ObjOnLoc",
            "sidetable.l": "ObjOnLoc",
            "sink.l": "ObjInLoc",
            "sinkbasin.l": "ObjInLoc",
            "sofa.l": "ObjOnLoc",
            "stoveburner.l": "ObjOnLoc",
            "tabletop.l": "ObjOnLoc",
            "toaster.l": "ObjInLoc",
            "toilet.l": "ObjInLoc",
            "toiletpaperhanger.l": "ObjInLoc",
            "towelholder.l": "ObjInLoc",
            "tvstand.l": "ObjOnLoc",
            "shelvingunit.l": "ObjOnLoc",
            "garbagebag.l": "ObjInLoc",
            "stool.l": "ObjOnLoc",
            "bottle.l": "ObjInLoc",
            "aluminumfoil.l": "ObjOnLoc",
            "dogbed.l": "ObjOnLoc",
            "roomdecor.l": "ObjInLoc",
            "tabletopdecor.l": "ObjOnLoc",
            "vacuumcleaner.l": "ObjInLoc",
        }
    }
}